// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/callback.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/plugins/index.tsx";
import * as $5 from "./routes/signin.ts";
import * as $6 from "./routes/signout.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/callback.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/plugins/index.tsx": $4,
    "./routes/signin.ts": $5,
    "./routes/signout.ts": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
